<?php

/**
 * Implementation of hook_content_default_fields().
 */
function cod_publication_content_default_fields() {
  $fields = array();

  // Exported field: field_attachment
  $fields['publication-field_attachment'] = array(
    'field_name' => 'field_attachment',
    'type_name' => 'publication',
    'display_settings' => array(
      'weight' => '-2',
      'parent' => '',
      'label' => array(
        'format' => 'inline',
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '2' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '3' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'token' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'filefield',
    'required' => '0',
    'multiple' => '0',
    'module' => 'filefield',
    'active' => '1',
    'list_field' => '1',
    'list_default' => 1,
    'description_field' => '0',
    'widget' => array(
      'file_extensions' => 'txt jpg jpeg doc pdf gif png',
      'file_path' => 'attachments',
      'progress_indicator' => 'bar',
      'max_filesize_per_file' => '',
      'max_filesize_per_node' => '',
      'insert' => 1,
      'insert_styles' => array(
        'image' => 'image',
        'imagecache_Large' => 'imagecache_Large',
        'imagecache_Medium' => 'imagecache_Medium',
        'imagecache_Small' => 'imagecache_Small',
        'auto' => 0,
        'link' => 0,
        'imagecache_cart' => 0,
        'imagecache_product' => 0,
        'imagecache_product_full' => 0,
        'imagecache_product_list' => 0,
        'imagecache_sponsor_logo_bronze' => 0,
        'imagecache_sponsor_logo_callout' => 0,
        'imagecache_sponsor_logo_gold' => 0,
        'imagecache_sponsor_logo_platinum' => 0,
        'imagecache_sponsor_logo_silver' => 0,
        'imagecache_uc_thumbnail' => 0,
      ),
      'insert_default' => 'auto',
      'insert_class' => '',
      'insert_width' => '',
      'label' => 'Attachment',
      'weight' => '-4',
      'description' => '',
      'type' => 'filefield_widget',
      'module' => 'filefield',
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Attachment');

  return $fields;
}
